version: '3'

tasks:
  test:
    - cls
    - pytest -v __tests 

  build-vue-component:
    dir: vue_component
    cmds:
      - pnpm run build

  dist: 
    - task: build-vue-component
    - poetry build

  rel: 
    - task: dist
    - poetry publish

  dev-ins: poetry install

