name: Build Vue Component
description: Builds a Vue component


runs:
  using: "composite"
  steps:
    - name: set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash
    - name: install dependencies
      run: pnpm install
      shell: bash
      working-directory: vue_component
    - name: build vue component
      shell: bash
      run: pnpm run build
      working-directory: vue_component